# Generated by Django 4.2.30 on 2026-09-14 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp number')),
                ('child_subject', models.CharField(blank=True, choices=[('mathematics', 'Mathematics'), ('computer_science', 'Computer Science'), ('other', 'Other / Not sure yet')], max_length=20, verbose_name="Child's subject")),
                ('child_curriculum', models.CharField(blank=True, max_length=150, verbose_name="Child's curriculum/board")),
                ('child_level', models.CharField(blank=True, max_length=100, verbose_name="Child's level/grade")),
                ('message', models.TextField(blank=True)),
                ('source_page', models.CharField(blank=True, help_text='Page the inquiry was submitted from.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_time', models.DateTimeField()),
                ('timezone', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='leads.lead')),
            ],
            options={
                'ordering': ['-requested_time'],
            },
        ),
    ]
