# Generated by Django 4.2.30 on 2026-09-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='location',
            field=models.CharField(blank=True, help_text='e.g. "Singapore" or "London, UK".', max_length=100),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, help_text='Star rating out of 5.'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='subject',
            field=models.CharField(choices=[('mathematics', 'Mathematics'), ('computer_science', 'Computer Science')], default='mathematics', max_length=20),
        ),
    ]
