# Generated by Django 4.2.30 on 2026-09-17 07:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='Used in the URL, e.g. "why-primes-refuse-to-behave".', unique=True)),
                ('category', models.CharField(choices=[('mathematics', 'Mathematics'), ('computer_science', 'Computer Science')], max_length=20)),
                ('excerpt', models.TextField(help_text='Short teaser shown on the blog grid.')),
                ('body', models.TextField(help_text='Full article body, shown on the article detail page.')),
                ('author', models.CharField(default='DigitAndData Team', max_length=100)),
                ('read_time_minutes', models.PositiveIntegerField(default=6, help_text='Approximate reading time in minutes.')),
                ('published_at', models.DateField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at'],
            },
        ),
    ]
