# Generated by Django 4.2.30 on 2026-09-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(help_text='Used in the URL, e.g. "ib".', unique=True)),
                ('category', models.CharField(choices=[('international', 'International'), ('national', 'National / Regional'), ('test_prep', 'Standardized Test / Competitive')], max_length=20)),
                ('level_range', models.CharField(blank=True, help_text='e.g. "Grades 6-12" or "Ages 11-18".', max_length=100)),
                ('summary', models.TextField(blank=True, help_text='Short description shown on the hub page.')),
                ('syllabus_outline', models.TextField(blank=True, help_text='Longer outline shown on the board detail page.')),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers sort first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mathematics Curriculum',
                'verbose_name_plural': 'Mathematics Curricula',
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
